name: Main

on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - uses: actions/setup-ruby@v1
      with: 
        ruby-version: '2.6'

    - name: Bump version      
      run: |
        gem install gem-release
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        gem bump
