name: Main

on: [push]

jobs: 
  release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v1

      - name: Release It
        uses: qbantek/release-after-tag
        with:
          rubygems_api_key: 1
 
