name: Main

on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - uses: actions/setup-ruby@v1
      with: 
        ruby-version: '2.6'

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - name: Bump version      
      run: |
        gem install -N gem-release
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        gem bump --skip-ci --version ${{ steps.get_version.outputs.VERSION }}
        git push origin HEAD:master
        gem release --verbose --key 8c58e6918aab40d3c01b871a8a5173a2
